[server]
address = "0.0.0.0"
port = 3000

[env] # Enviromental variables
db-connection = "DB_CONNECTION_URL"
g-auth-client-id = "G_AUTH_CLIENT_ID"
g-auth-secret = "G_AUTH_SECRET"
redirect-url = "REDIRECT_URL"