[package]
name = "chat-plugin-database"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
diesel_migrations = "2.1.0"
log = "0.4.20"
serde = "1.0.194"
uuid = "1.6.1"
diesel = { version = "2.0.0", features = ["postgres", "chrono", "r2d2", "uuid"] }